name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: docker://barksim/bark:latest
    
    steps:
    - name: Setting up virtual environment
      run: |
        virtualenv -p python3 ./python/venv  --system-site-packages
        source ./python/venv/bin/activate
        pip install -r tools/installers/requirements.txt -q
    - name: Runing bazel test
      run: bazel //...
