name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: docker://barksim/bark:latest
    
    steps:
    - name: Run a one-line script
      run: virtualenv -p python3 ./python/venv  --system-site-packages
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
