name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: docker://barksim/bark:latest
    steps:
      - uses: actions/checkout@v1
      - name: Setting up virtual environment
        run: virtualenv -p python3 ./bark/python_wapper/venv  --system-site-packages
      - name: Getting into venv
        run: . ./bark/python_wapper/venv/bin/activate
      - name: Runing bazel test
        run: bazel test //...
