name: ManyLinux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: docker://mansoorcheema/bazel-manylinux
    steps:
      - uses: actions/checkout@v1
      - name: Setting up virtual environment
        run: virtualenv --python=/opt/python/cp37-cp37m/bin/python ./bark/python_wrapper/venv
      - name: Getting into venv
        run: . ./bark/python_wrapper/venv/bin/activate && ls ./bark/python_wrapper/venv/
      - name: Installing Requirements
        run: echo $PATH && pip3 install -r ./tools/installers/requirements.txt
      - name: Building ManyLinux
        run: bash package.sh manylinux
