name: ManyLinux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: docker://mansoorcheema/bazel-manylinux
    steps:
      - uses: actions/checkout@v1
      - name: Setting up virtual environment
        run: /opt/python/cp37-cp37m/bin/virtualenv -p python3 ./bark/python_wrapper/venv --system-site-packages
      - name: Getting into venv
        run: . ./bark/python_wrapper/venv/bin/activate
      - name: Installing Requirements
        run: pip3 install -r ./tools/installers/requirements.txt
      - name: Building ManyLinux
        run: bash package.sh manylinux
