name: ManyLinux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: docker://mansoorcheema/bazel-manylinux
    steps:
      - uses: actions/checkout@v1
      - name: Setting up virtual environment
        run: virtualenv --python=/opt/python/cp37-cp37m/bin/python .bark/bark/python_wrapper/venv
      - name: Getting into venv
        run: source ./bark/bark/python_wrapper/venv/bin/activate
      - name: Installing Requirements
        run: pip install -r ./bark/tools/installers/requirements.txt
      - name: Building Mnaylinux
        run: bash ./bark/package.sh manylinux
